[package]
name = "tp-lexer"
authors = ["Linfeng Chen <chenlinfeng25@outlook.com>"]
version = "0.1.0"
edition = "2024"
homepage = "https://github.com/Starry-OS/tp-lexer"
repository = "https://github.com/Starry-OS/tp-lexer"


[dependencies]
